### ISSUE TITLE
Conexion y levante

### ISSUE THREAD

**Issue by jbaldarr** [project-openubl/xsender-server#10]
Hola Amigo, me gustaría levantar el servicio en Ubuntu y enviar los documentos desde un sistema windows.

Estoy sufriendo un poco con la aplicación en si, no he podido ejecutarla, quisiera saber que debo instalar más, aparte de visual studio code, tengo quarkus corriendo junto con minio , por eso he instalado ubuntu en otra pc y he puesto todo en 0, para levantar xsender exclusivamente.

**Comment by carlosthe19916** [comment]
Hola @jbaldarr ,
>NOTA: necesitas JDK 11 instalado.

Si quieres levantar la aplicación en modo desarrollo puedes seguir los siguientes pasos:

```
git clone https://github.com/project-openubl/xsender-server.git
cd xsender-server
./mvnw install -DskipTests
./mvnw compile quarkus:dev -f api/ -DnoDeps
```

Eso es todo, el servidor se encuentra corriendo en http://localhost:8080/

Puedes enviar tus comprobantes usando cualquier llamada HTTP, ejemplo usando Postman:

![Screenshot from 2020-10-23 08-14-07](https://user-images.githubusercontent.com/2582866/96963257-a3fb2900-1508-11eb-98f7-f35f354d5740.png)

La configuración por defecto no requiere minio ni ningun servidor de mensajeria. Estas son las opciones que tienes:

- Donde almacenar tus archivos: `fylesystem`, `s3` => `filesystem` para almacenar tus archivos en tu disco duro, y `s3` para almacenar tus archivos en Amazon o Minio. El cambio lo puedes hacer acá https://github.com/project-openubl/xsender-server/blob/master/api/src/main/resources/application.properties#L22

- Cómo reenviar comprobantes cuando la SUNAT está caída: `basic` y `jms`. `basic` para que el software cree jobs internos y reenvie los comprobantes cada cierto tiempo, y `jms` para tener un servidor de mensajería que se encarga de reenviar los comprobantes según esté configurado tu servidor de mensajería. El cambio lo puedes hacer acá https://github.com/project-openubl/xsender-server/blob/master/api/src/main/resources/application.properties#L35

## En modo producción
Para producción debes de correr:
```
./mvnw install -DskipTests
```

buscar los ejecutables java en:
- `api/target/xsender-server-api-***-runner.jar`
-  y `api/target/lib`

copiar y pegar esas dos cosas y ejecutar tu programa como cualquier programa java:

`java -jar myEjecutable.jar`

> NOTA: También puedes hacer que el .jar de producción se ejecute como un servicio del sistema operativo, hay muchos tutoriales en la web.

**Comment by carlosthe19916** [comment]
Algo más. Si quieres ejecutar xsender-server y acceder desde afuera a él debes de hacer que Quarkus escuche en todas las interfaces de red usando la propiedad `quarkus.http.host`:
- https://stackoverflow.com/questions/55043764/how-to-make-quarkus-to-listen-on-all-network-interfaces-instead-of-localhost
- https://quarkus.io/guides/all-config#quarkus-container-image-openshift_quarkus.openshift.native-arguments

**Comment by jbaldarr** [comment]
Gracias por responder, ya felizmente pude poner todo al 100% y estoy corriendo modo dev el proyecto,  ya  tengo a quarkus , xsender configurado y lo puedo ver desde otra pc sin problemas **quisiera apoyar con el desarrollo de una vista del estado de los documentos, filtrados por tipo y fecha**, estoy realizando pruebas, pero trabajo mas en c# y entorno windows, actualmente puedo firmar los documentos desde mi aplicacion y el envio de documentos me estaba volviendo loco. ¡¡¡ Felicitaciones es un proyecto genial!!!
![xsender](https://user-images.githubusercontent.com/13920076/97065522-87e0a180-1573-11eb-9d58-176a37c360c8.png)

**Comment by carlosthe19916** [comment]
@jbaldarr Que bueno que pudiste levantar el servidor sin problemas.
Acabo de empezar a trabajar en el UI y algunos cambios en el backend que serán lanzados en la siguiente version. Esta es la UI https://github.com/project-openubl/xsender-server-ui . La idea de poder filtrar documentos me parece una buena idea y será implementada también. También estoy abriendo un canal de Chat donde puedes ponerte en contacto con el proyecto, el link es https://projectopenubl.zulipchat.com Puedes escribir preguntas también allí.

**Comment by jbaldarr** [comment]
👍
Chevere...

**Comment by jbaldarr** [comment]
necesito una invitacion

**Comment by carlosthe19916** [comment]
@jbaldarr tienes razón. Este nuevo link debería de funcionar: https://projectopenubl.zulipchat.com/join/alzft7jvj4stsni6nxbvntof/
